namespace SND_Vol
{
    [default_interface]
    runtimeclass AudioProfile : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AudioProfile();

        String ProfileName{ get; set; };
        Windows.Foundation.Collections.IMap<String, Single> AudioLevels{ get; set; };
        Windows.Foundation.Collections.IMap<String, Boolean> AudioStates{ get; set; };
        Boolean IsDefaultProfile{ get; set; };
    }
}
