import "HotKeyView.idl";
import "AudioProfile.idl";

namespace SND_Vol
{
    [default_interface]
    runtimeclass SecondWindow : Microsoft.UI.Xaml.Window
    {
        SecondWindow();

        IObservableVector<HotKeyView> HotKeys{ get; };
    }
}
