import "AudioProfile.idl";
import "NavigationBreadcrumbBarItem.idl";

namespace SND_Vol
{
    [default_interface]
    runtimeclass SecondWindow : Microsoft.UI.Xaml.Window
    {
        SecondWindow();

        static SecondWindow Current{ get; };

        IObservableVector<NavigationBreadcrumbBarItem> Breadcrumbs{ get; };
        Windows.Graphics.RectInt32 DisplayRect{ get; };
        Microsoft.UI.WindowId Id{ get; };
    }
}
